#!/bin/sh
#
# .bashrc.d/20-alias
#

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias df='df -h'
alias du='du -h'

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

alias :q='exit'
alias diff='diff -bptuwBN'
alias tmux='tmux -u'
alias vi='vim'

case $OSNAME in
  FreeBSD | Darwin)
    alias psx='ps axo "user,pid,ppid,%cpu,%mem,tt,state,start,command"' ;;
  Linux)
    alias psx='ps axo "user,pid,ppid,%cpu,%mem,tt,state,stime,command"' ;;
  *)
    ;;
esac

which vim &>/dev/null && {
  VIMRUNTIME=$(vim -es +'.!echo $VIMRUNTIME' +%p +q!)
  test -f $VIMRUNTIME/macros/less.sh && {
    alias less=$VIMRUNTIME/macros/less.sh
  }
}
