#!/bin/bash

#
# https://gist.github.com/simonjbeaumont/4672606
#

tmup () {
    echo -n "Updating to latest tmux environment...";
    local IFS=",";
    for line in $(tmux showenv -t $(tmux display -p "#S") | tr "\n" ",");
    do
        if [[ $line == -* ]]; then
            unset $(echo $line | cut -c2-);
        else
            export $line;
        fi;
    done;
    echo "Done"
}
